### ISSUE TITLE
Validation Messages

### ISSUE THREAD

**Issue by johnellison** [johnellison/solve-the-refugee-crisis#7]
The current validation messages on the join form for the website are the default messages. In `main.js` they have been customized, but for some reason aren't appearing...

<img width="876" alt="screen shot 2015-11-17 at 12 42 37 pm" src="https://cloud.githubusercontent.com/assets/5806135/11211633/b9174624-8d28-11e5-86c1-cbe227a81035.png">

**Comment by osilviotti** [comment]
This was due to jQuery validate requiring name attributes on the fields which is how it matches what string to show in the messages object
