### ISSUE TITLE
Join auto-scrolling firing inappropriately

### ISSUE THREAD

**Issue by osilviotti** [johnellison/solve-the-refugee-crisis#8]
Clicking the `Join` button in the nav jumps you down to the correct section. If I then scroll back up to the nav and hover over any other link, I get jumped back down to the join section preventing me from clicking other links

Using Chrome 46

**Comment by johnellison** [comment]
Hey @ollie101 thanks for raising this. I think it is the same issue as #4 by the looks of it unless I'm misunderstanding what you've written.

**Comment by abigailfoster** [comment]
I reproduced it this morning.  It is definitely related to #4 but Ollie raises a more significant issue:  Once you click 'Join', if you scroll to the top and simply mouse-over the 'Playbook' link for instance, it jumps back to the Join section, but the same behavior repeats every time until you refresh the page.  With issue #4 it was doing the jump back once, which was a nuisance, but you could just scroll back down and click the link again and it would work the second time.  The current issue actually makes certain links un-clickable without a total page refresh.

**Comment by osilviotti** [comment]
Sent a pull request that fixes both issues
